POST http://localhost:3000/users/signup
Content-Type: application/json

    {
        "username" : "Aryaman",
        "email" : "SwarnimBhai@gmail.com",
        "password" : "Arn"
    }
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
        "email" : "SwarnimBhai@gmail.com",
        "password" : "Arn"
}   
###
GET http://localhost:3000/events/
Content-Type: application/json

{
    "id" : "65860c6cbde9eafba916f934"
}
###
POST http://localhost:3000/events/add
Content-Type: application/json

{
    "event_manager" : "65860c6cbde9eafba916f934",
    "startTime"     : "aaj bhaiya ji ",
    "endTime"       : "kl bhaiya ji ",
    "coordinators"  :  null,
    "participants"  :  [
        {
            "name"  :  "Aryaman Chandra",
            "email" :   "Aryamanch14@gmail.com",
            "isPresent" : false
        }
    ]
}
######