POST http://localhost:3000/users/signup
Content-Type: application/json

    {
        "username" : "Aryaman",
        "email" : "SwarnimBhai@gmail.com",
        "password" : "Arn"
    }
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "ancaaa@wreu@gmail.com",
    "password":"Arn"
}   
###
GET http://localhost:3000/events/
Content-Type: application/json

{
    "id" : "6581ecc55b3587b7e48e9347"
}
###
POST http://localhost:3000/events/add
Content-Type: application/json

{
    "Event_Manager" : "6581ecc55b3587b7e48e9347",
    "startTime"     : "aaj bhaiya ji ",
    "endTime"       : "kl bhaiya ji ",
    "Coordinators"  :  null,
    "Participants"  :  null
}
###